package com.ghx.auto.cm.regression.ui.smoke.angularjs;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.ghx.auto.cm.ui.angularjs.page.RegistrationUI;
import com.ghx.auto.core.support.excel.ExcelRow;
import com.ghx.auto.core.ui.test.AbstractAutoUITest;

public class RegistrationUI_Test extends AbstractAutoUITest{
	
	@Test(priority=1, groups = "functional", dataProvider = "RegUIDP", enabled = false)                                         
	public void Registration_UI_Network_Registration(int rowNo, ExcelRow row){
		
		get(RegistrationUI.class)
			.invoke_url()
			.wait_for_landing_page_to_load()
		    .verify_enter_email_chevron("Enter Email Address")
		    .verify_enter_email_welcomemessage("Welcome to GHX's New Supplier Registration Process.")
		    .verify_ghx_footer("For the Privacy Terms, © 2015 Global Healthcare Exchange, LLC. All rights reserved.")
		    .verify_ghx_terms_of_use("Terms of use")
		    .verify_ghx_privacy_policy("Privacy Policy")
		    .verify_ghx_site_map("Site Map")
		    .enter_email_id(row.get_column_string_value(1))
		    .wait_for_enter_email_next_button_clickable()
		    .click_enter_email_next_button()
		    .wait_until_loading_bar_to_complete()
		    .wait_for_select_company_chevron_to_load()
		    .wait_for_add_company_not_listed_button_to_load()
		    .verify_select_company_chevron_header("Step 2: Select Your Company")
		    .wait_for_add_company_not_listed_button_clickable()
		    .click_add_company_not_listed_button()
		    .wait_for_setup_company_chevron_to_load()
		    .wait_for_validate_and_next_button_to_load()
		    .wait_for_validate_and_next_button_clickable()
		    .verify_setup_company_chevron_header("Step 3: Setup Your Company")
		    .wait_until(5)
		    .enter_legal_business_name(row.get_column_string_value(2))
		    .enter_federal_tax_id(row.get_column_string_value(3))
		    .enter_street_address1(row.get_column_string_value(4))
		    .enter_street_address2(row.get_column_string_value(5))
		    .enter_city(row.get_column_string_value(6))
		    .enter_zipcode(row.get_column_string_value(7))
		    .wait_until(1)
		    .select_state_from_dropdown(row.get_column_string_value(8))
		    .wait_until(1)
		    .select_country_from_dropdown(row.get_column_string_value(9))
		    .wait_until(1)
		    .click_validate_and_next_button()
		    
		    .wait_until_loading_bar_to_complete()
		    .click_normalization_pop_up_select_btn()
		    
		    .wait_for_create_account_chevron_to_load()
		    .wait_until(5)
		    .select_salutation_from_dropdown(row.get_column_string_value(10))
		    .enter_first_name(row.get_column_string_value(11))
		    .enter_last_name(row.get_column_string_value(12))
		    .enter_middle_name(row.get_column_string_value(13))
		    .enter_suffix(row.get_column_string_value(14))
		    .enter_work_phone(row.get_column_string_value(15))
		    .enter_job_title(row.get_column_string_value(16))
		    .enter_cell_phone(row.get_column_string_value(17))
		    .click_eula_checkbox()
		    .click_create_account_chevron_submit_button()
		    .wait_until(5)
		    .verify_create_account_popup_text_header("Please Do Not Close this Window")
		    .click_create_account_popup_text_continue_button()
		    .wait_until(5)
		    .enter_validate_account_temp_password("gltd123")
		    .enter_validate_account_custom_password("gltd@123")
		    .wait_for_custom_password_check_to_load()
		    .enter_validate_account_confirm_password("gltd@123")
		    .wait_for_confirm_password_check_to_load()
		    .wait_for_validate_account_submit_button_clickable()
		    .click_validate_account_submit_button()
		    .wait_until(5)
		    //.verify_confirm_and_login_chevron_header("Step 6: Login to Register and Connect")
		    .wait_for_confirm_and_login_onboardcm_button_clickable()
		    .wait_for_confirm_and_login_onboardsm_button_clickable()
		    .click_confirm_and_login_onboardcm_button()
	        .wait_until(5)	
	        .enter_search_for_account_search_field(row.get_column_string_value(18))
	        .wait_until(1)
	        //.wait_for_search_for_account_search_button_clickable()
	        .click_search_for_account_search_button()
	        .wait_until(3)
	        //.wait_for_search_for_account_register_button_clickable()
	        .verify_health_system_present_in_row_1(row.get_column_string_value(20))
	        .click_search_for_account_register_button()
	        .wait_until(3)
	        //.wait_for_search_for_account_popup_express_button_clickable()
	        .verify_search_for_account_popup_text(row.get_column_string_value(19))
	        .wait_for_search_for_account_popup_no_button_clickable()
	        .click_search_for_account_popup_no_button()
	        .wait_until(5)
	        
	        .verify_express_health_system_details_customername(row.get_column_string_value(20))
	        .verify_express_health_system_details_customeraddress(row.get_column_string_value(21))
	        .verify_express_health_system_details_customercity(row.get_column_string_value(22))
//defect//  .verify_express_health_system_details_customerzip(row.get_column_string_value(23))
	        .verify_express_health_system_details_customerurl(row.get_column_string_value(24))
	        .wait_for_express_health_system_details_next_button_clickable()
	        .click_express_health_system_details_next_button()
	        .wait_until_loading_bar_to_complete()
	        //.wait_until(10)
	        .select_express_payment_cardtype(row.get_column_string_value(25))
	        .enter_express_payment_cardnumber(row.get_column_string_value(26))
	        .enter_express_payment_nameoncard(row.get_column_string_value(27))
	        .select_express_payment_expirationmonth(row.get_column_string_value(28))
	        .select_express_payment_expirationyear(row.get_column_string_value(29))
	        .enter_express_payment_verificationnumber(row.get_column_string_value(30))
	        .enter_express_payment_billingst(row.get_column_string_value(31))
	        .enter_express_payment_billingcity(row.get_column_string_value(32))
	        .select_express_payment_billingstate(row.get_column_string_value(33))
	        .select_express_payment_billingcountry(row.get_column_string_value(34))
	        .enter_express_payment_billingzip(row.get_column_string_value(35))
	        .enter_express_payment_billingemail(row.get_column_string_value(36))
	        .click_express_payment_checkbox1()
	        .click_express_payment_checkbox2()
	        .click_express_payment_checkbox3()
	        .click_express_payment_checkbox4()
	        .click_express_payment_chargeandcontinue_button()
	        .wait_until_loading_bar_to_complete()
	        
	       // .click_payment_received_popup_next_button()
	        
	      //  .wait_until(10)
	        .select_express_company_details_business_type(row.get_column_string_value(37))
	        .select_express_company_details_amount_of_business(row.get_column_string_value(38))
	        .enter_express_company_details_company_website(row.get_column_string_value(39))
	        .click_express_company_details_phi1_option("Yes")
	        .click_express_company_details_phi2_option("Yes")
	        .click_express_company_details_next_button()
	        .wait_until_loading_bar_to_complete()
	        //.wait_until(10)
	        .enter_contacts_sales_first_name(row.get_column_string_value(40))
	        .enter_contacts_sales_last_name(row.get_column_string_value(41))
	        .enter_contacts_sales_email(row.get_column_string_value(42))
	        .click_contacts_next_button()
	        .wait_until_loading_bar_to_complete()
		 	//.wait_until(10)
		 	.enter_diversity_majority_owner_etnicity(row.get_column_string_value(43))
		 	.click_diversity_majority_owner_gender_male()
		 	.click_diversity_next_button()
		 	.wait_until_loading_bar_to_complete()
		 	//.wait_until(5)
		 	.verify_doc_name_row_1(row.get_column_string_value(44))
		 	.verify_upload_status(row.get_column_string_value(45))
		 	.click_upload_link()
		 	.click_continue_button()
		 	.wait_until_loading_bar_to_complete()
		 	.wait_until(3)
		 	.enter_expiration_date(row.get_column_string_value(46),row.get_column_string_value(47),row.get_column_string_value(48))
		 	.upload_doc_file(row.get_column_string_value(49))
		 	.wait_for_document_to_upload(row.get_column_string_value(50))
		 	.click_save_button()
		 	.verify_doc_name_row_1(row.get_column_string_value(44))
		 	.verify_upload_status(row.get_column_string_value(51))
		 	.click_doc_upload_next_button()
		 	.verify_ack_name_row_1(row.get_column_string_value(52))
		 	.verify_ack_status(row.get_column_string_value(53))
		 	.click_ack_link()
		 	.click_ack_popup_yes_button()
		 	.verify_ack_provided_by_name(row.get_column_string_value(54))
		 	.verify_ack_status(row.get_column_string_value(55))
		 	.click_ack_page_next_button()
		 	.wait_until_loading_bar_to_complete()
		 	.wait_until(5)
		 	.check_eula_license_aggement_checkbox()
		 	.click_agreement_page_next_button()
		 	.wait_until_loading_bar_to_complete()
		 	.wait_until(5)
		 	.click_health_system_request_popup_next_button()
		 	.wait_until_loading_bar_to_complete()
		 //	.wait_until(5)
		 	.select_available_onboarding_category(row.get_column_string_value(57))
		 	.move_category_available_to_used()
		 	.click_onboarding_category_page_save_and_next_button()
		 	.wait_until_loading_bar_to_complete()
		 //	.wait_until(5)
		 	.enter_company_affiliate_fein(row.get_column_string_value(58))
		 	.enter_contact_first_name(row.get_column_string_value(59))
		 	.select_do_you_accept_edi_transmissions(row.get_column_string_value(60))
			.select_is_your_company_iso_certified(row.get_column_string_value(61))
		 	.click_form_page_save_and_continue_button()
		 	.click_alert_notify_person_no_button()
		 	.verify_doc_type_row_1(row.get_column_string_value(62))
		 	.verify_doc_status_row_1(row.get_column_string_value(63))
		 	.clear_cookies();
	}

	 @DataProvider (name="RegUIDP")
	  	public Object[][] getExcelDataForRegUI() {
		  Object[][] data = getExcelClient("EXCEL_REGUI").get_all_rows_except_header();
		  return data;
	 }
	 
	@Test(priority=2, groups = "functional", dataProvider = "RegUIDPExisting", enabled = false)                                         
		public void registrationUINewUserRegistrationInExistingVendor(int rowNo, ExcelRow row){
			
			get(RegistrationUI.class)
				.invoke_url()
				.wait_for_landing_page_to_load()
			    .verify_enter_email_chevron("Enter Email Address")
			    .verify_enter_email_welcomemessage("Welcome to GHX's New Supplier Registration Process.")
			    .verify_ghx_footer("For the Privacy Terms, © 2015 Global Healthcare Exchange, LLC. All rights reserved.")
			    .verify_ghx_terms_of_use("Terms of use")
			    .verify_ghx_privacy_policy("Privacy Policy")
			    .verify_ghx_site_map("Site Map")
			    .enter_email_id(row.get_column_string_value(1))
			    .wait_for_enter_email_next_button_clickable()
			    .click_enter_email_next_button()
			    .wait_until_loading_bar_to_complete()
			    .wait_for_select_company_chevron_to_load()
			    .wait_for_add_company_not_listed_button_to_load()
			    .verify_select_company_chevron_header("Step 2: Select Your Company")
			    .wait_for_add_company_not_listed_button_clickable()
			    .enter_your_company_tax_id(row.get_column_string_value(3))
			    .wait_until_loading_bar_to_complete()
			    .click_option_1_from_fein_dropdown()
			    .wait_until_loading_bar_to_complete()
			    .verify_tax_id_row_no(1, row.get_column_string_value(3))
	// defect   .verify_legal_business_name_row_no(1, row.get_column_string_value(2))
			    /*.verify_address_row_no(1, 	row.get_column_string_value(4)
			    							+ ", "
			    							+ row.get_column_string_value(5)
			    							+ ", "
			    							+ row.get_column_string_value(6)
			    							+ ", "
			    							+ row.get_column_string_value(8)
			    							+ ", "
			    							+ row.get_column_string_value(9))*/
			    							
			    .click_select_button_present_on_row_no(1)
			    .wait_until_loading_bar_to_complete()
			    .wait_until(5)
			    .verify_legal_business_name_on_setup_company_page(row.get_column_string_value(2))
			    .verify_fein_on_setup_company_page(row.get_column_string_value(3))
			    .verify_street_add_1_on_setup_company_page(row.get_column_string_value(4))
			  //  .verify_street_add_2_on_setup_company_page(row.get_column_string_value(5))
			   // .verify_country_on_setup_company_page(row.get_column_string_value(9))
			    .verify_state_on_setup_company_page(row.get_column_string_value(8))
			    .verify_city_on_setup_company_page(row.get_column_string_value(6))
			    .verify_zip_on_setup_company_page(row.get_column_string_value(7))
			    .click_next_button_on_setup_company_page()
			    .select_salutation_from_dropdown(row.get_column_string_value(10))
			    .enter_first_name(row.get_column_string_value(11))
			    .enter_last_name(row.get_column_string_value(12))
			    .enter_middle_name(row.get_column_string_value(13))
			    .enter_suffix(row.get_column_string_value(14))
			    .enter_work_phone(row.get_column_string_value(15))
			    .enter_job_title(row.get_column_string_value(16))
			    .enter_cell_phone(row.get_column_string_value(17))
			    .click_eula_checkbox()
			    .click_create_account_chevron_submit_button()
			    .wait_until(5)
			    .verify_create_account_popup_text_header("Please Do Not Close this Window")
			    .click_create_account_popup_text_continue_button()
			    .wait_until(5)
			    .enter_validate_account_temp_password("gltd123")
			    .enter_validate_account_custom_password("gltd@123")
			    .wait_for_custom_password_check_to_load()
			    .enter_validate_account_confirm_password("gltd@123")
			    .wait_for_confirm_password_check_to_load()
			    .wait_for_validate_account_submit_button_clickable()
			    .click_validate_account_submit_button()
			    .wait_until(5)
			    .wait_for_confirm_and_login_onboardcm_button_clickable()
			    .wait_for_confirm_and_login_onboardsm_button_clickable()
			    .click_confirm_and_login_onboardcm_button()
		        .wait_until(5)	
		        .enter_search_for_account_search_field(row.get_column_string_value(18))
		        .wait_until(1)
		        .click_search_for_account_search_button()
		        .wait_until(3)
		        .verify_health_system_present_in_row_1(row.get_column_string_value(20))
		        .click_search_for_account_register_button()
		        .wait_until(3)
		        .verify_search_for_account_popup_text(row.get_column_string_value(19))
		        .wait_for_search_for_account_popup_no_button_clickable()
		        .click_search_for_account_popup_no_button()
		        .wait_until(5)
		        
		        .verify_express_health_system_details_customername(row.get_column_string_value(20))
		        .verify_express_health_system_details_customeraddress(row.get_column_string_value(21))
		        .verify_express_health_system_details_customercity(row.get_column_string_value(22))
	//defect//  .verify_express_health_system_details_customerzip(row.get_column_string_value(23))
		        .verify_express_health_system_details_customerurl(row.get_column_string_value(24))
		        .wait_for_express_health_system_details_next_button_clickable()
		        .click_express_health_system_details_next_button()
		        .wait_until_loading_bar_to_complete()
		        .wait_until(5)
		        .verify_express_company_details_legal_name(row.get_column_string_value(2))
		        .verify_express_company_details_tax_id(row.get_column_string_value(3))
		        .verify_express_company_details_business_type(row.get_column_string_value(37))
		        .verify_express_company_details_amount_of_business(row.get_column_string_value(38))
		        .verify_express_company_details_company_website(row.get_column_string_value(39))
		        .verify_express_company_details_phi1_option("yes")
		        .verify_express_company_details_phi2_option("yes")
		        .click_express_company_details_next_button()
		        .wait_until_loading_bar_to_complete()
		        .wait_until(5)
		        .verify_contacts_sales_first_name(row.get_column_string_value(40))
		        .verify_contacts_sales_last_name(row.get_column_string_value(41))
		        .verify_contacts_sales_email(row.get_column_string_value(42))
		        .click_contacts_next_button()
		        .wait_until_loading_bar_to_complete()

		        .verify_diversity_majority_owner_etnicity(row.get_column_string_value(43))
			 	.verify_diversity_majority_owner_gender_male()
			 	.click_diversity_next_button()
			 	.wait_until_loading_bar_to_complete()

			 	.verify_doc_name_row_1(row.get_column_string_value(44))
			 	.verify_upload_status(row.get_column_string_value(51))
			 	.click_doc_upload_next_button()
			 	
			 	.verify_ack_name_row_1(row.get_column_string_value(52))
			 	.verify_ack_status(row.get_column_string_value(53))
			 	.click_ack_link()
			 	.click_ack_popup_yes_button()
			 	.verify_ack_provided_by_name(row.get_column_string_value(54))
			 	.verify_ack_status(row.get_column_string_value(55))
			 	.click_ack_page_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(5)
			 	.check_eula_license_aggement_checkbox()
			 	.click_agreement_page_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(5)
			 	.click_health_system_request_popup_next_button()
			 	.wait_until_loading_bar_to_complete()

			 	.verify_used_onboaring_category(1, row.get_column_string_value(57))
			 	.click_onboarding_category_page_save_and_next_button()
			 	.wait_until_loading_bar_to_complete()

			 	.verify_company_affiliate_fein(row.get_column_string_value(58))
			 	.verify_contact_first_name(row.get_column_string_value(59))
			 	.verify_do_you_accept_edi_transmissions(row.get_column_string_value(60))
				.verify_is_your_company_iso_certified(row.get_column_string_value(61))
			 	.click_form_page_save_and_continue_button()
			 	.click_alert_notify_person_no_button()
			 	.verify_doc_type_row_1(row.get_column_string_value(62))
			 	.verify_doc_status_row_1(row.get_column_string_value(63))
			 	.clear_cookies();
		}  
	 
	 @DataProvider (name="RegUIDPExisting")
	  	public Object[][] getExcelDataForRegUINewUserExistingVendor() {
		  Object[][] data = getExcelClient("EXCEL_REGUIEX").get_all_rows_except_header();
		  return data;
	 }
	 
	 
	 @Test(priority=3, groups = "functional", dataProvider = "RegUINormalReg")                                         
		public void registrationUINormalRegistration(int rowNo, ExcelRow row){
			
			get(RegistrationUI.class)
				.invoke_url()
				.wait_for_landing_page_to_load()
			    .verify_enter_email_chevron("Enter Email Address")
			    .verify_enter_email_welcomemessage("Welcome to GHX's New Supplier Registration Process.")
			    .verify_ghx_footer("For the Privacy Terms, © 2016 Global Healthcare Exchange, LLC. All rights reserved.")
			    .verify_ghx_terms_of_use("Terms of use")
			    .verify_ghx_privacy_policy("Privacy Policy")
			    .verify_ghx_site_map("Site Map")
			    .enter_email_id(row.get_column_string_value(1))
			    .wait_for_enter_email_next_button_clickable()
			    .click_enter_email_next_button()
			    .wait_until_loading_bar_to_complete()
			    .wait_for_select_company_chevron_to_load()
			    .wait_for_add_company_not_listed_button_to_load()
			    .verify_select_company_chevron_header("Step 2: Select Your Company")
			    .wait_for_add_company_not_listed_button_clickable()
			    
			    .click_add_company_not_listed_button()
			    
			    .wait_until_loading_bar_to_complete()
			    
			    .wait_for_setup_company_chevron_to_load()
			    .wait_for_validate_and_next_button_to_load()
			    .wait_for_validate_and_next_button_clickable()
			    .verify_setup_company_chevron_header("Step 3: Setup Your Company")
			    .enter_legal_business_name(row.get_column_string_value(2))
			    .enter_federal_tax_id(row.get_column_string_value(3))
			    .enter_street_address1(row.get_column_string_value(4))
			    .enter_street_address2(row.get_column_string_value(5))
			    .enter_city(row.get_column_string_value(6))
			    .enter_zipcode(row.get_column_string_value(7))
			    .select_state_from_dropdown(row.get_column_string_value(8))
			    //.select_country_from_dropdown(row.get_column_string_value(9))
			    .click_validate_and_next_button()
			    
			    .wait_until_loading_bar_to_complete()
			    .click_normalization_pop_up_select_btn()
			    
			    .select_salutation_from_dropdown(row.get_column_string_value(10))
			    .enter_first_name(row.get_column_string_value(11))
			    .enter_last_name(row.get_column_string_value(12))
			    .enter_middle_name(row.get_column_string_value(13))
			    .enter_suffix(row.get_column_string_value(14))
			    .enter_work_phone(row.get_column_string_value(15))
			    .enter_job_title(row.get_column_string_value(16))
			    .enter_cell_phone(row.get_column_string_value(17))
			    .click_eula_checkbox()
			    .click_create_account_chevron_submit_button()
			    .wait_until(5)
			    
			    .verify_create_account_popup_text_header("Please Do Not Close this Window")
			    .click_create_account_popup_text_continue_button()
			    .wait_until(5)
			    
			    .enter_validate_account_temp_password("gltd123")
			    .enter_validate_account_custom_password("gltd@123")
			    .wait_for_custom_password_check_to_load()
			    .enter_validate_account_confirm_password("gltd@123")
			    .wait_for_confirm_password_check_to_load()
			    .wait_for_validate_account_submit_button_clickable()
			    .click_validate_account_submit_button()
			    .wait_until(5)
			    
			    .wait_for_confirm_and_login_onboardcm_button_clickable()
			    .wait_for_confirm_and_login_onboardsm_button_clickable()
			    .click_confirm_and_login_onboardcm_button()
		        .wait_until(5)	
		        
		        .enter_search_for_account_search_field(row.get_column_string_value(18))
		        .click_search_for_account_search_button()
		        .verify_health_system_present_in_row_1(row.get_column_string_value(20))
		        .click_search_for_account_register_button()
		        .verify_search_for_account_popup_text(row.get_column_string_value(19))
		        .click_search_for_account_popup_yes_button()
		        .wait_until_loading_bar_to_complete()
		         
		        .verify_normal_health_system_details_customername(row.get_column_string_value(20))
		        .verify_normal_health_system_details_customeraddress(row.get_column_string_value(21))
		        .verify_normal_health_system_details_customercity(row.get_column_string_value(22))
	        	.verify_normal_health_system_details_customerzip(row.get_column_string_value(23))
		        .verify_normal_health_system_details_customerurl(row.get_column_string_value(24))
		        .click_normal_health_system_details_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .verify_legal_business_name_on_setup_company_page(row.get_column_string_value(2))
			    .verify_fein_on_setup_company_page(row.get_column_string_value(3))
			    .select_normal_company_details_business_type(row.get_column_string_value(37))
		        .click_normal_company_details_next_button()
		        .wait_until_loading_bar_to_complete()
			    
		        .click_normal_company_relationship_existing_relationship_option("no")
		        .select_normal_company_relationship_spend_tier(row.get_column_string_value(38))
		        .enter_normal_company_relationship_employee_count("5")
		        .click_normal_company_relationship_onsite_option("no")
		        .click_normal_company_relationship_q1_option("no")
		        .click_normal_company_relationship_q2_option("no")
		        .click_normal_company_relationship_q3_option("no")
		        .click_normal_company_relationship_q4_option("no")
		        .click_normal_company_relationship_q5_option("no")
		        .click_normal_company_relationship_phi1_option("no")
		        .click_normal_company_relationship_phi2_option("no")
		        .click_normal_company_relationship_next_button()
		        
		        .select_rep_risk_question_1("no")
		        .select_rep_risk_question_2("no")
		        .select_rep_risk_question_3("no")
		        .select_rep_risk_question_4("no")
		        .select_rep_risk_question_5("no")
		        .select_rep_risk_on_site_question("no")
		        .select_dynamic_question(1, "no")
		        .select_dynamic_question(2, "no")
		        .select_location("Los Angeles")
		        .select_department("Information Technology")
		        
		        
		        .click_your_relationship_page_next_button()
		        .wait_until_loading_bar_to_complete()
			 
		        .click_relationship_no_radio_button()
		        .click_affiliations_no_radio_button()
		        .click_compensation_no_radio_button()
		        .check_eula_license_aggement_checkbox()
		        .click_agreement_page_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .select_express_payment_cardtype(row.get_column_string_value(25))
		        .enter_express_payment_cardnumber(row.get_column_string_value(26))
		        .enter_express_payment_nameoncard(row.get_column_string_value(27))
		        .select_express_payment_expirationmonth(row.get_column_string_value(28))
		        .select_express_payment_expirationyear(row.get_column_string_value(29))
		        .enter_express_payment_verificationnumber(row.get_column_string_value(30))
		        .enter_express_payment_billingst(row.get_column_string_value(31))
		        .enter_express_payment_billingcity(row.get_column_string_value(32))
		        .select_express_payment_billingstate(row.get_column_string_value(33))
		        .select_express_payment_billingcountry(row.get_column_string_value(34))
		        .enter_express_payment_billingzip(row.get_column_string_value(35))
		        .enter_express_payment_billingemail(row.get_column_string_value(36))
		        .click_express_payment_checkbox1()
		        .click_express_payment_checkbox2()
		        .click_express_payment_checkbox3()
		        .click_express_payment_checkbox4()
		        .verify_express_payment_amount("$250.00")
		        .click_express_payment_chargeandcontinue_button()
		        .wait_until_loading_bar_to_complete()
		        .click_payment_received_popup_next_button()
		        
		        .wait_until_loading_bar_to_complete()
		        .verify_express_company_details_legal_name(row.get_column_string_value(2))
		        .verify_express_company_details_tax_id(row.get_column_string_value(3))
		        .verify_express_company_details_business_type("JONT")
		        .verify_express_company_details_amount_of_business("T5")
		        .enter_express_company_details_company_website(row.get_column_string_value(39))
		        .verify_express_company_details_phi1_option("no")
		        .verify_express_company_details_phi2_option("no")
		        .click_express_company_details_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .enter_contacts_sales_first_name(row.get_column_string_value(40))
		        .enter_contacts_sales_last_name(row.get_column_string_value(41))
		        .enter_contacts_sales_email(row.get_column_string_value(42))
		        .click_contacts_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .enter_diversity_majority_owner_etnicity(row.get_column_string_value(43))
			 	.click_diversity_majority_owner_gender_male()
			 	.click_diversity_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	
			 	.verify_doc_name_row_1(row.get_column_string_value(44))
			 	.verify_upload_status(row.get_column_string_value(45))
			 	.click_upload_link()
			 	.click_continue_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(3)
			 	.enter_expiration_date(row.get_column_string_value(46),row.get_column_string_value(47),row.get_column_string_value(48))
			 	.upload_doc_file(row.get_column_string_value(49))
			 	.wait_for_document_to_upload(row.get_column_string_value(50))
			 	.click_save_button()
			 	.verify_doc_name_row_1(row.get_column_string_value(44))
			 	.verify_upload_status(row.get_column_string_value(51))
			 	.click_doc_upload_next_button()
			 	
			 	.verify_ack_name_row_1(row.get_column_string_value(52))
			 	.verify_ack_status(row.get_column_string_value(53))
			 	.click_ack_link()
			 	.click_ack_popup_yes_button()
			 	.verify_ack_provided_by_name(row.get_column_string_value(54))
			 	.verify_ack_status(row.get_column_string_value(55))
			 	.click_ack_page_next_button()
			 	
			 	//.wait_until_loading_bar_to_complete()
			 	//.wait_until(5)
			 	//.check_eula_license_aggement_checkbox()
			 	//.click_agreement_page_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(5)
			 	.click_health_system_request_popup_next_button()
			 	
			 	.wait_until_loading_bar_to_complete()
			 //	.wait_until(5)
			 	.select_available_onboarding_category(row.get_column_string_value(57))
			 	.move_category_available_to_used()
			 	.click_onboarding_category_page_save_and_next_button()
			 	.wait_until_loading_bar_to_complete()
			 //	.wait_until(5)
			 	.enter_company_affiliate_fein(row.get_column_string_value(58))
			 	.enter_contact_first_name(row.get_column_string_value(59))
			 	.select_do_you_accept_edi_transmissions(row.get_column_string_value(60))
				.select_is_your_company_iso_certified(row.get_column_string_value(61))
			 	.click_form_page_save_and_continue_button()
			 	.click_alert_notify_person_no_button()
			 	.verify_doc_type_row_1(row.get_column_string_value(62))
			 	.verify_doc_status_row_1(row.get_column_string_value(63))
			 	.clear_cookies();
	 }	
	 
	 @DataProvider (name="RegUINormalReg")
	  	public Object[][] getExcelDataForRegUINormal() {
		  Object[][] data = getExcelClient("EXCEL_REGUINORMAL").get_all_rows_except_header();
		  return data;
	 }
	 
	 
	@Test(priority=4, groups = "functional", dataProvider = "RegUIExistingNormalReg")                                         
		public void registrationUIForExistingNormalRegistration(int rowNo, ExcelRow row){
			
			get(RegistrationUI.class)
				.invoke_url()
				.wait_for_landing_page_to_load()
			    .verify_enter_email_chevron("Enter Email Address")
			    .verify_enter_email_welcomemessage("Welcome to GHX's New Supplier Registration Process.")
			    .verify_ghx_footer("For the Privacy Terms, © 2015 Global Healthcare Exchange, LLC. All rights reserved.")
			    .verify_ghx_terms_of_use("Terms of use")
			    .verify_ghx_privacy_policy("Privacy Policy")
			    .verify_ghx_site_map("Site Map")
			    .enter_email_id(row.get_column_string_value(1))
			    .wait_for_enter_email_next_button_clickable()
			    .click_enter_email_next_button()
			    .wait_until_loading_bar_to_complete()
			    .wait_for_select_company_chevron_to_load()
			    .wait_for_add_company_not_listed_button_to_load()
			    .verify_select_company_chevron_header("Step 2: Select Your Company")
			    .wait_for_add_company_not_listed_button_clickable()
		//  .enter_legal_business_name_on_select_company_page("Hoana Medical Inc")
			    .wait_until(4)
			//    .click_select_button_in_select_company_page()
			    .wait_until_loading_bar_to_complete()
			    .click_validate_and_next_button()
			    
			    .wait_until_loading_bar_to_complete()
			    
			    
			    .select_salutation_from_dropdown(row.get_column_string_value(10))
			    .enter_first_name(row.get_column_string_value(11))
			    .enter_last_name(row.get_column_string_value(12))
			    .enter_middle_name(row.get_column_string_value(13))
			    .enter_suffix(row.get_column_string_value(14))
			    .enter_work_phone(row.get_column_string_value(15))
			    .enter_job_title(row.get_column_string_value(16))
			    .enter_cell_phone(row.get_column_string_value(17))
			    .click_eula_checkbox()
			    .click_create_account_chevron_submit_button()
			    .wait_until(5)
			    
			    .verify_create_account_popup_text_header("Please Do Not Close this Window")
			    .click_create_account_popup_text_continue_button()
			    .wait_until(5)
			    
			    .enter_validate_account_temp_password("gltd123")
			    .enter_validate_account_custom_password("gltd@123")
			    .wait_for_custom_password_check_to_load()
			    .enter_validate_account_confirm_password("gltd@123")
			    .wait_for_confirm_password_check_to_load()
			    .wait_for_validate_account_submit_button_clickable()
			    .click_validate_account_submit_button()
			    .wait_until(5)
			    
			    .wait_for_confirm_and_login_onboardcm_button_clickable()
			    .wait_for_confirm_and_login_onboardsm_button_clickable()
			    .click_confirm_and_login_onboardcm_button()
		        .wait_until(5)	
		        
		        .enter_search_for_account_search_field(row.get_column_string_value(18))
		        .click_search_for_account_search_button()
		        .verify_health_system_present_in_row_1(row.get_column_string_value(20))
		        .click_search_for_account_register_button()
		        .verify_search_for_account_popup_text(row.get_column_string_value(19))
		        .click_search_for_account_popup_yes_button()
		        .wait_until_loading_bar_to_complete()
		         
		        .verify_normal_health_system_details_customername(row.get_column_string_value(20))
		        .verify_normal_health_system_details_customeraddress(row.get_column_string_value(21))
		        .verify_normal_health_system_details_customercity(row.get_column_string_value(22))
	        	.verify_normal_health_system_details_customerzip(row.get_column_string_value(23))
		        .verify_normal_health_system_details_customerurl(row.get_column_string_value(24))
		        .click_normal_health_system_details_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .verify_legal_business_name_on_setup_company_page(row.get_column_string_value(2))
			    .verify_fein_on_setup_company_page(row.get_column_string_value(3))
			    .select_normal_company_details_business_type(row.get_column_string_value(37))
		        .click_normal_company_details_next_button()
		        .wait_until_loading_bar_to_complete()
			    
		        .click_normal_company_relationship_existing_relationship_option("no")
		        .select_normal_company_relationship_spend_tier(row.get_column_string_value(38))
		        .enter_normal_company_relationship_employee_count("5")
		        .click_normal_company_relationship_onsite_option("no")
		        .click_normal_company_relationship_q1_option("no")
		        .click_normal_company_relationship_q2_option("no")
		        .click_normal_company_relationship_q3_option("no")
		        .click_normal_company_relationship_q4_option("no")
		        .click_normal_company_relationship_q5_option("no")
		        .click_normal_company_relationship_phi1_option("no")
		        .click_normal_company_relationship_phi2_option("no")
		        .click_normal_company_relationship_next_button()
		        
		        .select_rep_risk_question_1("no")
		        .select_rep_risk_question_2("no")
		        .select_rep_risk_question_3("no")
		        .select_rep_risk_question_4("no")
		        .select_rep_risk_question_5("no")
		        .select_rep_risk_on_site_question("no")
		        .select_dynamic_question(1, "no")
		        .select_dynamic_question(2, "no")
		        .select_location("Los Angeles")
		        .select_department("Information Technology")
		        
		        
		        .click_your_relationship_page_next_button()
		        .wait_until_loading_bar_to_complete()
			 
		        .click_relationship_no_radio_button()
		        .click_affiliations_no_radio_button()
		        .click_compensation_no_radio_button()
		        .check_eula_license_aggement_checkbox()
		        .click_agreement_page_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .select_express_payment_cardtype(row.get_column_string_value(25))
		        .enter_express_payment_cardnumber(row.get_column_string_value(26))
		        .enter_express_payment_nameoncard(row.get_column_string_value(27))
		        .select_express_payment_expirationmonth(row.get_column_string_value(28))
		        .select_express_payment_expirationyear(row.get_column_string_value(29))
		        .enter_express_payment_verificationnumber(row.get_column_string_value(30))
		        .enter_express_payment_billingst(row.get_column_string_value(31))
		        .enter_express_payment_billingcity(row.get_column_string_value(32))
		        .select_express_payment_billingstate(row.get_column_string_value(33))
		        .select_express_payment_billingcountry(row.get_column_string_value(34))
		        .enter_express_payment_billingzip(row.get_column_string_value(35))
		        .enter_express_payment_billingemail(row.get_column_string_value(36))
		        .click_express_payment_checkbox1()
		        .click_express_payment_checkbox2()
		        .click_express_payment_checkbox3()
		        .click_express_payment_checkbox4()
		        .verify_express_payment_amount("$25.00")
		        .click_express_payment_chargeandcontinue_button()
		        .wait_until_loading_bar_to_complete()
		        .click_payment_received_popup_next_button()
		        
		        .wait_until_loading_bar_to_complete()
		        .verify_express_company_details_legal_name(row.get_column_string_value(2))
		        .verify_express_company_details_tax_id(row.get_column_string_value(3))
		        .verify_express_company_details_business_type("JONT")
		        .verify_express_company_details_amount_of_business("T5")
		        .enter_express_company_details_company_website(row.get_column_string_value(39))
		        .verify_express_company_details_phi1_option("no")
		        .verify_express_company_details_phi2_option("no")
		        .click_express_company_details_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .enter_contacts_sales_first_name(row.get_column_string_value(40))
		        .enter_contacts_sales_last_name(row.get_column_string_value(41))
		        .enter_contacts_sales_email(row.get_column_string_value(42))
		        .click_contacts_next_button()
		        .wait_until_loading_bar_to_complete()
		        
		        .enter_diversity_majority_owner_etnicity(row.get_column_string_value(43))
			 	.click_diversity_majority_owner_gender_male()
			 	.click_diversity_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	
			 	.verify_doc_name_row_1(row.get_column_string_value(44))
			 	.verify_upload_status(row.get_column_string_value(45))
			 	.click_upload_link()
			 	.click_continue_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(3)
			 	.enter_expiration_date(row.get_column_string_value(46),row.get_column_string_value(47),row.get_column_string_value(48))
			 	.upload_doc_file(row.get_column_string_value(49))
			 	.wait_for_document_to_upload(row.get_column_string_value(50))
			 	.click_save_button()
			 	.verify_doc_name_row_1(row.get_column_string_value(44))
			 	.verify_upload_status(row.get_column_string_value(51))
			 	.click_doc_upload_next_button()
			 	.verify_ack_name_row_1(row.get_column_string_value(52))
			 	.verify_ack_status(row.get_column_string_value(53))
			 	.click_ack_link()
			 	.click_ack_popup_yes_button()
			 	.verify_ack_provided_by_name(row.get_column_string_value(54))
			 	.verify_ack_status(row.get_column_string_value(55))
			 	.click_ack_page_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(5)
			 	.check_eula_license_aggement_checkbox()
			 	.click_agreement_page_next_button()
			 	.wait_until_loading_bar_to_complete()
			 	.wait_until(5)
			 	.click_health_system_request_popup_next_button()
			 	.wait_until_loading_bar_to_complete()
			 //	.wait_until(5)
			 	.select_available_onboarding_category(row.get_column_string_value(57))
			 	.move_category_available_to_used()
			 	.click_onboarding_category_page_save_and_next_button()
			 	.wait_until_loading_bar_to_complete()
			 //	.wait_until(5)
			 	.enter_company_affiliate_fein(row.get_column_string_value(58))
			 	.enter_contact_first_name(row.get_column_string_value(59))
			 	.select_do_you_accept_edi_transmissions(row.get_column_string_value(60))
				.select_is_your_company_iso_certified(row.get_column_string_value(61))
			 	.click_form_page_save_and_continue_button()
			 	.click_alert_notify_person_no_button()
			 	.verify_doc_type_row_1(row.get_column_string_value(62))
			 	.verify_doc_status_row_1(row.get_column_string_value(63))
			 	.clear_cookies();
	 }	
	 
	 @DataProvider (name="RegUIExistingNormalReg")
	  	public Object[][] getExcelDataForExistingRegUINormal() {
		  Object[][] data = getExcelClient("EXCEL_REGUINORMALEX").get_all_rows_except_header();
		  return data;
	 }
	 
	 
	 
		
	
	 
	 
	 	  
}
